# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - go-openhacks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # Run on a Windows machine to match your Azure App Service environment
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Create .env file and run build
        # Use PowerShell for the Windows environment
        shell: pwsh
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" | Out-File -FilePath .env.local -Encoding utf8 -Append
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" | Out-File -FilePath .env.local -Encoding utf8 -Append
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" | Out-File -FilePath .env.local -Encoding utf8 -Append
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" | Out-File -FilePath .env.local -Encoding utf8 -Append
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" | Out-File -FilePath .env.local -Encoding utf8 -Append
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" | Out-File -FilePath .env.local -Encoding utf8 -Append
          
          npm install
          npx prisma generate
          npm run build --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32620E2CD0054EDAB498AE60CBBDFD6C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DBA790D5D0814532B4DA7D6CB0DD8E99 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0C4EF574E6C4F6F814D91BD6918169B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'go-openhacks'
          slot-name: 'Production'
          package: .
